### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [lirios/workspace#10]
Profile 'gcc' created for '/usr/bin/g++'.
Creating profile 'qt5'.
Setting profile 'gcc' as the base profile for this profile.
Skipping prl file '/usr/lib/libQt5dtkwidget.prl', because it cannot be opened (No such file or directory).
Skipping prl file '/usr/lib/libQt5AV.prl', because it cannot be opened (No such file or directory).
Skipping prl file '/usr/lib/libQt5WebKit.prl', because it cannot be opened (No such file or directory).
Skipping prl file '/usr/lib/libQt5AVWidgets.prl', because it cannot be opened (No such file or directory).
Skipping prl file '/usr/lib/libQt5Fluid.prl', because it cannot be opened (No such file or directory).
Skipping prl file '/usr/lib/libQt5WebKitWidgets.prl', because it cannot be opened (No such file or directory).
Skipping prl file '/usr/lib/libQt5dtkcore.prl', because it cannot be opened (No such file or directory).
Build graph does not yet exist for configuration 'default'. Starting from scratch.
Resolving project for configuration default
ERROR: /home/solaraquarion/build/liri-workspace-git/src/workspace/powermanager/powermanager.qbs:3:1 Error while handling product 'liri-powermanager':
/home/solaraquarion/build/liri-workspace-git/src/workspace/powermanager/powermanager.qbs:9:5 Dependency 'Qt5GSettings' not found for product 'liri-powermanager'.

**Comment by plfiorini** [comment]
AUR package has the dependency.
It was introduced 6 months ago: https://github.com/lirios/packages/commit/eaaccdc72ccdca95c1e3d401a56837f82517d223
Can't reproduce this issue on the CI which performs clean builds in a container.
This smells like an issue on your side.
