### ISSUE TITLE
Redesign liri-screenshot UI

### ISSUE THREAD

**Issue by plfiorini** [lirios/workspace#7]
UI is disgusting, redesign!

**Comment by crutchcorn** [comment]
Picture of current one? Feature set?

**Comment by plfiorini** [comment]
This is the quick and dirty UI I came up originally:

![screenshot from 2017-03-04 08-04-15](https://cloud.githubusercontent.com/assets/843710/23576912/a3d88f18-00b1-11e7-8d0c-953d5b60e511.png)
![screenshot from 2017-03-04 08-04-28](https://cloud.githubusercontent.com/assets/843710/23576913/a904d7ee-00b1-11e7-9710-c9504c1e02ca.png)

This is how it has changed in my local copy (not pushed yet):

![screenshot from 2017-03-04 08-01-36](https://cloud.githubusercontent.com/assets/843710/23576919/c175fede-00b1-11e7-8e94-e2090a72065a.png)

![screenshot from 2017-03-04 08-01-16](https://cloud.githubusercontent.com/assets/843710/23576921/c5415d10-00b1-11e7-943f-0644b20fcd62.png)

The idea behind the app is pretty simple. You select what you want to grab:
* whole screen
* active window
* a specific window
* an area
Only the first option is implemented at the moment.
You can also show the cursor in the final image or add a the decoration to the captured window.

**Comment by plfiorini** [comment]
Made it less verbose. "Option" is now "Grab" and the combo box has the following options:
* This screen
* Active window
* Specific window
* Area

App bar title is now "Screen capture" and the "Take screenshot" button is now "Capture".

**Comment by crutchcorn** [comment]
Honestly, I think this would be served better as an applet of some kind.
Having it be an entire application is a bit clunky given how fast and
unexpected screenshots tend to be. I personally would rather tap out a few
settings than to open an entire app. (also I like key combos) ;)

**Comment by Aldrog** [comment]
@crutchcorn having a screenshot app doesn't cancel availability of PrtScn, Alt+PrtScn. It just allows more complex actions like taking a screenshot of a window without it's border or capturing a mouse-selected area.

**Comment by crutchcorn** [comment]
Right, and I get that. But does it have to be a full windowed application?
I just feel that it's too small of a thing to be it's own app. Perhaps a
settings page?

**Comment by Aldrog** [comment]
Settings doesn't feel like a very logical place to me. Screenshot is an action, and it doesn't affect system state in any way.

Also, I don't get what is the problem with small apps.

**Comment by plfiorini** [comment]
I agree with @Aldrog Settings is not the right place. Worth mentioning there are keyboard shortcuts for all the complex actions as well as this small UI for people who are not into keyboard commands.

**Comment by crutchcorn** [comment]
Here are my thoughts;
If these are settings for the screenshot button on the keyboard, let's put
them in settings. Otherwise, if this is an app to take screenshots, let's
make it as minimal as possible (let's do a draggable FAB where one of the
popups would be settings where if you select only part of the screen, the
rest would be dimmed?) or something like Peek GIF but material (line a live
preview of what you'll be taking a screenshot of with only a screenshot
button at the bottom and a settings button)
